services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres1234"]
      interval: 5s
      timeout: 5s
      retries: 5


  app:
    build: ./
    container_name: fastapi_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:1234@db:5432/postgres1234
    ports:
      - "8000:8000"
    networks:
      - app_network
    volumes:
      - .:/Fastapi_app


volumes:
  postgres_data:


networks:
  app_network:
    driver: bridge